sudo: required
dist: trusty

env:
  matrix:
    - SIM_MODEL=ILD_l5_v02 REC_MODEL=ILD_l5_o1_v02
   # - SIM_MODEL=ILD_s5_v02 REC_MODEL=ILD_s5_o1_v02
   # - SIM_MODEL=ILD_l5_v02 REC_MODEL=ILD_l5_o2_v02
   # - SIM_MODEL=ILD_s5_v02 REC_MODEL=ILD_s5_o2_v02

services:
  - docker

language: cpp

before_install:
  - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install cvmfs cvmfs-config-default
  - rm -f cvmfs-release-latest_all.deb
  - wget https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
  - sed -i s/clicdp.cern.ch/ilc.desy.de/ default.local
  - sudo mkdir -p /etc/cvmfs
  - sudo mv default.local /etc/cvmfs/default.local
  - sudo /etc/init.d/autofs stop
  - sudo cvmfs_config setup
  - sudo mkdir -p /cvmfs/ilc.desy.de
  - sudo mount -t cvmfs ilc.desy.de /cvmfs/ilc.desy.de
  - ls /cvmfs/ilc.desy.de

# command to install dependencies
install:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package

# command to run tests
script:
  - docker run -it --name CI_container -e SIM_MODEL=$SIM_MODEL -e REC_MODEL=$REC_MODEL -v $PKGDIR:/home/ilc/data/Package -v /cvmfs/clicdp.cern.ch:/cvmfs/clicdp.cern.ch -d engineren/centos7-ilc /bin/bash
  #- docker exec -it CI_container /bin/bash -c "./Package/.travis-ci.d/test.sh";
  

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
